CREATE TABLE IF NOT EXISTS user_match (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  university_id INT NOT NULL,
  gender CHAR(1) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  match_score DECIMAL(7,4) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
